---
title: 【JavaScript】Promise 规范与重写实现
date: 2021-01-09
categories:
 - frontEnd
author: ReisenD
tags:
 - javascript
 - ES6
 - 面试
---

## Promise 的状态
* **pending**: promise 的初始状态，在此状态下可 settled 至 **fulfilled** 或 **rejected** 状态
* **fulfilled**: 解决状态，此状态代表 promise 已执行成功，私有值被 resolve 函数执行，这个私有值通常记为 value。此状态下不可再改变状态
* **rejected**: 拒绝状态，表示 promise 执行失败，私有值被 reject，这个私有值记为 reason。此状态下不可再改变状态

## then 方法
1. then 方法接收 2 个函数参数，参数可选。如果参数不为函数则忽略  
2. 参数函数将会异步执行，会放置于队列中等待下一轮微任务  
3. 调用 onFulfilled 函数，将 Promise 的 value 值作为参数传入  
4. 调用 onRejectd 函数，将 Promise 的 reason 值作为参数传入  
5. then 函数会返回一个 Promise  
6. then 可被多次调用  

## 尝试手写
1. 使用 class 创建构造函数方式
2. 使用 Symbol 变量创建 3 种 状态
3. 构造函数接收一个 exec 方法，resolve 与 reject 将是这两个方法的参数
```js
// 定义 3 个状态
const Pending = Symbol('Pending')
const Fulfilled = Symbol('Fulfilled')
const Rejected = Symbol('Rejected')

class MyPromise{
    constructor(exec) {
        this.state = Pending
        this.value = undefined; // 存储 exec 执行成功结果
        this.reason = undefined; // 存储 exec 执行失败原因
        this.onFulfilled = [];  // 执行成功时的回调函数集合
        this.onRejected = [];   // 执行失败时的回调函数集合
        // 定义 resolve 与 reject 方法
        // 只有状态为 Pending 时才进行改变
        const resolve = value => {
            if (this.state === Pending) {
                this.state = Fulfilled
                // 成功时设置 exec 结果，执行成功回调函数
                this.value = value;
                this.onFulfilled.forEach(fn => fn())
            }
        }
        const reject = reason => {
            if (this.state === Rejected) {
                this.state = Rejected;
                // 失败时设置 exec 原因，执行失败回调函数
                this.reason = reason;
                this.onRejected.forEach(fn => fn())
            }
        }
        // 函数参数将以这 2 个函数方式执行
        exec(resolve, reject)
        // 构造函数设置完成，该类可进行初始化传参 new MyPromise((resolve, reject) => {})
    }
    then(onFulfilled, onRejected) {
        // 设置判断是否定义函数
        let isDef = fn => fn && typeof fn === 'function'
        let myPromise;
        // 如果是完成状态
        if (this.state === Fulfilled) {
            // 在定义了该方法时，以 return 的方式返回 myPromise 结果，因为 then 可以链式调用
            if (isDef(onFulfilled)) {
                return myPromise = new MyPromise((resolve, reject) => {
                    try {
                        // 这个 value 是上一次 then 的返回值
                        let value = onFulfilled(this.value)
                        resolve(value)
                    } catch (reason) {
                        reject(reason)
                    }
                })
            }
        }
        // 如果是失败状态-同上
        if (this.status === Rejected) {
            if (isDef(onRejected)) {
                return myPromise = new MyPromise((resolve, reject) => {
                    try {
                        let value = onRejected(this.value)
                        resolve(value)
                    } catch (reason) {
                        reject(reason)
                    }
                })
            }
        }
        // 如果是初始状态, 说明尚未注册, 将方法进行注册
        if (this.status === Pending) {
            // 同样, 该结果需要返回一个 MyPromise 对象以供链式调用
            return myPromise = new MyPromise((resolve, reject) => {
                try {
                    if (isDef(onFulfilled)) {
                        this.onFulfilled.push(() => {
                            let value = onFulfilled(this.value)
                            resolve(value)
                        })
                    }
                    if (isDef(onRejected)) {
                        this.onRejected.push(() => {
                            let value = onRejected(this.reason)
                            resolve(value)
                        })
                    }
                } catch (reason) {
                    reject(reason)
                }
            })
        }
    }
    // catch 方法就是调用 then 方法
    catch(onRejected) {
        return this.then(null, onRejected)
    }
}
```